apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: todo-chatbot
spec:
  selector:
    app: todo-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort